using DemoApp.Views.Base;

namespace DemoApp.Views.Layouts.Scroll;

/// <summary>
/// Four things that are actually bigger than the box holding them, because that is the only state in which a
/// viewport is a viewport at all.
/// </summary>
/// <remarks>Each group's scroll properties are read off what the screen is for rather than chosen to show a value.</remarks>
internal sealed class ScrollExamplesView : DemoExamplesView, IUIViewDefinition
{
    public static string ViewKey => "demo.layouts.scroll.examples";

    protected override string ComponentRoute => "/layouts/scroll";
    protected override DemoViewKind[] AvailableKinds => [DemoViewKind.Main, DemoViewKind.Examples, DemoViewKind.Scenarios];
    protected override string Header => "demo.layouts.scroll.header";
    protected override string HeaderDescription => "demo.layouts.scroll.description";

    protected override void DrawContent(WrapPanelComponent container)
        => _ = container.AddChildren(DemoUI.CreateColumns([CreateListGroup(), CreateConversationGroup()], [CreatePictureGroup(), CreateTableGroup()]));

    /// <summary>
    /// More rows than room, down only: sideways would take each row's trailing state out of sight.
    /// </summary>
    private static ContainerComponent CreateListGroup()
    {
        return DemoUI.CreateExample("More rows than room",
            new ScrollContainerComponent()
                .SetHeight(UILayoutLength.Absolute(280))
                .SetPadding(UIThickness.Uniform(12))
                .SetBorderThickness(UIThickness.Uniform(1))
                .SetBorderColor(UIThemeColor.Border)
                .VerticalScrollOnly()
                .AddChild(UILayout.Stack(2)
                    .AddChild(new ActionComponent()
                        .SetType(UIButtonType.Ghost)
                        .SetIcon(DemoIcons.Outline(DemoIcons.Check))
                        .SetIconColor(UIThemeColor.FromStyle(UIColorStyle.Success))
                        .SetTitle("billing · #481")
                        .SetDescription("Deployed 4 minutes ago")
                        .SetShowChevron(false)
                        .SetTrailingText("Details")
                    )
                    .AddChild(new ActionComponent()
                        .SetType(UIButtonType.Ghost)
                        .SetIcon(DemoIcons.Outline(DemoIcons.Undo))
                        .SetIconColor(UIThemeColor.FromStyle(UIColorStyle.Danger))
                        .SetTitle("dns · #127")
                        .SetDescription("Rolled back")
                        .SetShowChevron(false)
                        .SetTrailingText("Details")
                    )
                    .AddChild(new ActionComponent()
                        .SetType(UIButtonType.Ghost)
                        .SetIcon(DemoIcons.Outline(DemoIcons.Clock))
                        .SetIconColor(UIThemeColor.FromStyle(UIColorStyle.Warning))
                        .SetTitle("panel · #902")
                        .SetDescription("Waiting on approval")
                        .SetShowChevron(false)
                        .SetTrailingText("Details")
                    )
                    .AddChild(new ActionComponent()
                        .SetType(UIButtonType.Ghost)
                        .SetIcon(DemoIcons.Outline(DemoIcons.Check))
                        .SetIconColor(UIThemeColor.FromStyle(UIColorStyle.Success))
                        .SetTitle("billing-worker · #58")
                        .SetDescription("Deployed 20 minutes ago")
                        .SetShowChevron(false)
                        .SetTrailingText("Details")
                    )
                    .AddChild(new ActionComponent()
                        .SetType(UIButtonType.Ghost)
                        .SetIcon(DemoIcons.Outline(DemoIcons.Check))
                        .SetIconColor(UIThemeColor.FromStyle(UIColorStyle.Success))
                        .SetTitle("status-page · #311")
                        .SetDescription("Deployed an hour ago")
                        .SetShowChevron(false)
                        .SetTrailingText("Details")
                    )
                    .AddChild(new ActionComponent()
                        .SetType(UIButtonType.Ghost)
                        .SetIcon(DemoIcons.Outline(DemoIcons.Clock))
                        .SetIconColor(UIThemeColor.FromStyle(UIColorStyle.Warning))
                        .SetTitle("identity · #76")
                        .SetDescription("Waiting on approval")
                        .SetShowChevron(false)
                        .SetTrailingText("Details")
                    )
                    .AddChild(new ActionComponent()
                        .SetType(UIButtonType.Ghost)
                        .SetIcon(DemoIcons.Outline(DemoIcons.Check))
                        .SetIconColor(UIThemeColor.FromStyle(UIColorStyle.Success))
                        .SetTitle("edge-router · #1204")
                        .SetDescription("Deployed two hours ago")
                        .SetShowChevron(false)
                        .SetTrailingText("Details")
                    )
                    .AddChild(new ActionComponent()
                        .SetType(UIButtonType.Ghost)
                        .SetIcon(DemoIcons.Outline(DemoIcons.Undo))
                        .SetIconColor(UIThemeColor.FromStyle(UIColorStyle.Danger))
                        .SetTitle("object-storage · #44")
                        .SetDescription("Rolled back")
                        .SetShowChevron(false)
                        .SetTrailingText("Details")
                    )
                    .AddChild(new ActionComponent()
                        .SetType(UIButtonType.Ghost)
                        .SetIcon(DemoIcons.Outline(DemoIcons.Check))
                        .SetIconColor(UIThemeColor.FromStyle(UIColorStyle.Success))
                        .SetTitle("metrics · #19")
                        .SetDescription("Deployed yesterday")
                        .SetShowChevron(false)
                        .SetTrailingText("Details")
                    )
                    .AddChild(new ActionComponent()
                        .SetType(UIButtonType.Ghost)
                        .SetIcon(DemoIcons.Outline(DemoIcons.Check))
                        .SetIconColor(UIThemeColor.FromStyle(UIColorStyle.Success))
                        .SetTitle("scheduler · #615")
                        .SetDescription("Deployed yesterday")
                        .SetShowChevron(false)
                        .SetTrailingText("Details")
                    )
                )
        );
    }

    /// <summary>
    /// Down only, and already at the bottom when the page paints, where the newest line is.
    /// </summary>
    private static ContainerComponent CreateConversationGroup()
    {
        return DemoUI.CreateExample("A conversation",
            new ScrollContainerComponent()
                .SetHeight(UILayoutLength.Absolute(280))
                .SetPadding(UIThickness.Uniform(12))
                .SetBorderThickness(UIThickness.Uniform(1))
                .SetBorderColor(UIThemeColor.Border)
                .VerticalScrollOnly()
                .AnchorToEnd()
                .AddChild(UILayout.Stack(10)
                    .AddChild(new SurfaceComponent()
                        .SetSurface(UISurfaceStyle.Raised)
                        .SetMaxWidth(UILayoutLength.Absolute(300))
                        .SetHorizontalAlignment(UIAlignment.Start)
                        .SetPadding(UIThickness.All(10, 8, 10, 8))
                        .SetContent(UILayout.Stack(2)
                            .AddChild(new TextComponent()
                                .SetTitle("Robin")
                                .SetTitleType(UITextAppearance.Caption)
                                .SetTitleColor(UIThemeColor.Muted)
                            )
                            .AddChild(new ParagraphComponent()
                                .SetDescription("The staging deploy is stuck on the health check again.")
                                .SetDescriptionType(UITextAppearance.Body)
                            )
                        )
                    )
                    .AddChild(new SurfaceComponent()
                        .SetSurface(UISurfaceStyle.Tinted)
                        .SetBackground(UIThemeColor.Primary)
                        .SetMaxWidth(UILayoutLength.Absolute(300))
                        .SetHorizontalAlignment(UIAlignment.End)
                        .SetPadding(UIThickness.All(10, 8, 10, 8))
                        .SetContent(UILayout.Stack(2)
                            .AddChild(new TextComponent()
                                .SetTitle("You")
                                .SetTitleType(UITextAppearance.Caption)
                                .SetTitleColor(UIThemeColor.Muted)
                            )
                            .AddChild(new ParagraphComponent()
                                .SetDescription("Which replica?")
                                .SetDescriptionType(UITextAppearance.Body)
                            )
                        )
                    )
                    .AddChild(new SurfaceComponent()
                        .SetSurface(UISurfaceStyle.Raised)
                        .SetMaxWidth(UILayoutLength.Absolute(300))
                        .SetHorizontalAlignment(UIAlignment.Start)
                        .SetPadding(UIThickness.All(10, 8, 10, 8))
                        .SetContent(UILayout.Stack(2)
                            .AddChild(new TextComponent()
                                .SetTitle("Robin")
                                .SetTitleType(UITextAppearance.Caption)
                                .SetTitleColor(UIThemeColor.Muted)
                            )
                            .AddChild(new ParagraphComponent()
                                .SetDescription("Two of eight, both in eu-west.")
                                .SetDescriptionType(UITextAppearance.Body)
                            )
                        )
                    )
                    .AddChild(new SurfaceComponent()
                        .SetSurface(UISurfaceStyle.Tinted)
                        .SetBackground(UIThemeColor.Primary)
                        .SetMaxWidth(UILayoutLength.Absolute(300))
                        .SetHorizontalAlignment(UIAlignment.End)
                        .SetPadding(UIThickness.All(10, 8, 10, 8))
                        .SetContent(UILayout.Stack(2)
                            .AddChild(new TextComponent()
                                .SetTitle("You")
                                .SetTitleType(UITextAppearance.Caption)
                                .SetTitleColor(UIThemeColor.Muted)
                            )
                            .AddChild(new ParagraphComponent()
                                .SetDescription("Same pair as Tuesday. Rolling back to 480 while I look.")
                                .SetDescriptionType(UITextAppearance.Body)
                            )
                        )
                    )
                    .AddChild(new SurfaceComponent()
                        .SetSurface(UISurfaceStyle.Raised)
                        .SetMaxWidth(UILayoutLength.Absolute(300))
                        .SetHorizontalAlignment(UIAlignment.Start)
                        .SetPadding(UIThickness.All(10, 8, 10, 8))
                        .SetContent(UILayout.Stack(2)
                            .AddChild(new TextComponent()
                                .SetTitle("Robin")
                                .SetTitleType(UITextAppearance.Caption)
                                .SetTitleColor(UIThemeColor.Muted)
                            )
                            .AddChild(new ParagraphComponent()
                                .SetDescription("Rollback is green, traffic is on the old revision.")
                                .SetDescriptionType(UITextAppearance.Body)
                            )
                        )
                    )
                    .AddChild(new SurfaceComponent()
                        .SetSurface(UISurfaceStyle.Raised)
                        .SetMaxWidth(UILayoutLength.Absolute(300))
                        .SetHorizontalAlignment(UIAlignment.Start)
                        .SetPadding(UIThickness.All(10, 8, 10, 8))
                        .SetContent(UILayout.Stack(2)
                            .AddChild(new TextComponent()
                                .SetTitle("Alex")
                                .SetTitleType(UITextAppearance.Caption)
                                .SetTitleColor(UIThemeColor.Muted)
                            )
                            .AddChild(new ParagraphComponent()
                                .SetDescription("I have the logs — the gate times out on the migration, not the app.")
                                .SetDescriptionType(UITextAppearance.Body)
                            )
                        )
                    )
                    .AddChild(new SurfaceComponent()
                        .SetSurface(UISurfaceStyle.Tinted)
                        .SetBackground(UIThemeColor.Primary)
                        .SetMaxWidth(UILayoutLength.Absolute(300))
                        .SetHorizontalAlignment(UIAlignment.End)
                        .SetPadding(UIThickness.All(10, 8, 10, 8))
                        .SetContent(UILayout.Stack(2)
                            .AddChild(new TextComponent()
                                .SetTitle("You")
                                .SetTitleType(UITextAppearance.Caption)
                                .SetTitleColor(UIThemeColor.Muted)
                            )
                            .AddChild(new ParagraphComponent()
                                .SetDescription("Then it is the index rebuild. That ran long on Tuesday too.")
                                .SetDescriptionType(UITextAppearance.Body)
                            )
                        )
                    )
                    .AddChild(new SurfaceComponent()
                        .SetSurface(UISurfaceStyle.Raised)
                        .SetMaxWidth(UILayoutLength.Absolute(300))
                        .SetHorizontalAlignment(UIAlignment.Start)
                        .SetPadding(UIThickness.All(10, 8, 10, 8))
                        .SetContent(UILayout.Stack(2)
                            .AddChild(new TextComponent()
                                .SetTitle("Alex")
                                .SetTitleType(UITextAppearance.Caption)
                                .SetTitleColor(UIThemeColor.Muted)
                            )
                            .AddChild(new ParagraphComponent()
                                .SetDescription("Raising the gate to ten minutes and queueing 481 again.")
                                .SetDescriptionType(UITextAppearance.Body)
                            )
                        )
                    )
                )
        );
    }

    /// <summary>
    /// Both axes at once: the picture keeps its size and the box moves over it.
    /// </summary>
    private static ContainerComponent CreatePictureGroup()
    {
        return DemoUI.CreateExample("A picture larger than its box",
            new ScrollContainerComponent()
                .SetHeight(UILayoutLength.Absolute(240))
                .SetPadding(UIThickness.Uniform(12))
                .SetBorderThickness(UIThickness.Uniform(1))
                .SetBorderColor(UIThemeColor.Border)
                .SetScroll(UIScrollMode.Auto, UIScrollMode.Auto)
                .AddChild(new ImageComponent()
                    .SetSource(DemoImages.HarbourSky)
                    .SetFit(UIImageFit.Cover)
                    .SetWidth(UILayoutLength.Absolute(900))
                    .SetHeight(UILayoutLength.Absolute(560))
                )
        );
    }

    /// <summary>
    /// Sideways only: the rows are as tall as they need to be and the page carries them.
    /// </summary>
    private static ContainerComponent CreateTableGroup()
    {
        return DemoUI.CreateExample("More columns than room",
            new ScrollContainerComponent()
                .HorizontalScrollOnly()
                .SetPadding(UIThickness.Uniform(12))
                .SetBorderThickness(UIThickness.Uniform(1))
                .SetBorderColor(UIThemeColor.Border)
                .AddChild(UILayout.Stack(0)
                    // A rule under the head only: a box round every cell would read as a spreadsheet.
                    .AddChild(new ContainerComponent()
                        .SetBorderThickness(UIThickness.All(0, 0, 0, 1))
                        .SetBorderColor(UIThemeColor.Border)
                        .SetPadding(UIThickness.All(0, 0, 0, 6))
                        .AddChild(new StackPanelComponent()
                            .SetOrientation(UIOrientation.Horizontal)
                            .SetSpacing(0)
                            .AddChild(new TextComponent().SetTitle("Service").SetTitleType(UITextAppearance.Overline).SetTitleColor(UIThemeColor.Muted).SetWidth(UILayoutLength.Absolute(160)))
                            .AddChild(new TextComponent().SetTitle("Release").SetTitleType(UITextAppearance.Overline).SetTitleColor(UIThemeColor.Muted).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("Environment").SetTitleType(UITextAppearance.Overline).SetTitleColor(UIThemeColor.Muted).SetWidth(UILayoutLength.Absolute(130)))
                            .AddChild(new TextComponent().SetTitle("Replicas").SetTitleType(UITextAppearance.Overline).SetTitleColor(UIThemeColor.Muted).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("Started").SetTitleType(UITextAppearance.Overline).SetTitleColor(UIThemeColor.Muted).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("Duration").SetTitleType(UITextAppearance.Overline).SetTitleColor(UIThemeColor.Muted).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("Result").SetTitleType(UITextAppearance.Overline).SetTitleColor(UIThemeColor.Muted).SetWidth(UILayoutLength.Absolute(130)))
                        )
                    )
                    .AddChild(new ContainerComponent()
                        .SetPadding(UIThickness.All(0, 6, 0, 6))
                        .AddChild(new StackPanelComponent()
                            .SetOrientation(UIOrientation.Horizontal)
                            .SetSpacing(0)
                            .AddChild(new TextComponent().SetTitle("billing").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(160)))
                            .AddChild(new TextComponent().SetTitle("#481").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("production").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(130)))
                            .AddChild(new TextComponent().SetTitle("8 of 8").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("17:04").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("4 m 12 s").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("Passed").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(130)))
                        )
                    )
                    .AddChild(new ContainerComponent()
                        .SetPadding(UIThickness.All(0, 6, 0, 6))
                        .AddChild(new StackPanelComponent()
                            .SetOrientation(UIOrientation.Horizontal)
                            .SetSpacing(0)
                            .AddChild(new TextComponent().SetTitle("dns").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(160)))
                            .AddChild(new TextComponent().SetTitle("#127").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("staging").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(130)))
                            .AddChild(new TextComponent().SetTitle("2 of 4").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("16:51").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("11 m 03 s").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("Rolled back").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(130)))
                        )
                    )
                    .AddChild(new ContainerComponent()
                        .SetPadding(UIThickness.All(0, 6, 0, 6))
                        .AddChild(new StackPanelComponent()
                            .SetOrientation(UIOrientation.Horizontal)
                            .SetSpacing(0)
                            .AddChild(new TextComponent().SetTitle("panel").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(160)))
                            .AddChild(new TextComponent().SetTitle("#902").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("staging").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(130)))
                            .AddChild(new TextComponent().SetTitle("4 of 4").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("16:40").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("2 m 55 s").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("Waiting").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(130)))
                        )
                    )
                    .AddChild(new ContainerComponent()
                        .SetPadding(UIThickness.All(0, 6, 0, 6))
                        .AddChild(new StackPanelComponent()
                            .SetOrientation(UIOrientation.Horizontal)
                            .SetSpacing(0)
                            .AddChild(new TextComponent().SetTitle("billing-worker").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(160)))
                            .AddChild(new TextComponent().SetTitle("#58").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("production").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(130)))
                            .AddChild(new TextComponent().SetTitle("3 of 3").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("16:22").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("1 m 47 s").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("Passed").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(130)))
                        )
                    )
                    .AddChild(new ContainerComponent()
                        .SetPadding(UIThickness.All(0, 6, 0, 6))
                        .AddChild(new StackPanelComponent()
                            .SetOrientation(UIOrientation.Horizontal)
                            .SetSpacing(0)
                            .AddChild(new TextComponent().SetTitle("edge-router").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(160)))
                            .AddChild(new TextComponent().SetTitle("#1204").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("production").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(130)))
                            .AddChild(new TextComponent().SetTitle("12 of 12").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("15:58").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(90)))
                            .AddChild(new TextComponent().SetTitle("6 m 30 s").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(110)))
                            .AddChild(new TextComponent().SetTitle("Passed").SetTitleType(UITextAppearance.Body).SetWidth(UILayoutLength.Absolute(130)))
                        )
                    )
                )
        );
    }
}
