using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using NE.Standard.UI.Generators.Infrastructure;

namespace NE.Standard.UI.Generators.RecursiveMembers;

/// <summary>Generates change-tracking plumbing for members annotated with <c>[RecursiveMember]</c>.</summary>
/// <remarks>
/// Symbols are read and validated in the transform (<see cref="RecursiveMemberModelFactory"/>); what reaches the output is
/// equatable data only, so an edit that changes no model re-emits nothing.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class RecursiveMemberGenerator : IIncrementalGenerator
{
    // Tracking names the incrementality tests read the steps' run reasons by.
    internal const string MemberModelsStep = "RecursiveMemberModels";
    internal const string CollectedModelsStep = "RecursiveMemberCollectedModels";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<RecursiveMemberModel>> members = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                RecursiveMemberNames.AttributeMetadataName,
                predicate: static (node, _) => node is PropertyDeclarationSyntax or IndexerDeclarationSyntax,
                transform: static (ctx, ct) => RecursiveMemberModelFactory.CreateMemberModel(ctx, ct))
            .Where(static model => model is not null)
            .Select(static (model, _) => model!)
            .WithTrackingName(MemberModelsStep)
            .Collect()
            .WithTrackingName(CollectedModelsStep);

        context.RegisterSourceOutput(members, static (ctx, members) => Execute(ctx, members));
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<RecursiveMemberModel> members)
    {
        if (members.IsDefaultOrEmpty)
            return;

        foreach ((RecursiveOwnerModel owner, List<RecursiveMemberModel> ownerMembers) in GroupByOwner(members))
        {
            GeneratedTypeModel declaration = owner.Declaration;

            var hasErrors = false;

            if (!declaration.IsPartial)
            {
                context.ReportDiagnostic(Diagnostic.Create(RecursiveMemberDiagnostics.OwnerMustBePartial, declaration.Location?.ToLocation(), declaration.DisplayName));

                hasErrors = true;
            }

            if (!owner.IsOrdinaryClass)
            {
                context.ReportDiagnostic(Diagnostic.Create(RecursiveMemberDiagnostics.OwnerMustBeOrdinaryClass, declaration.Location?.ToLocation(), declaration.DisplayName));

                hasErrors = true;
            }

            if (!owner.InheritsRecursiveObservable)
            {
                context.ReportDiagnostic(Diagnostic.Create(RecursiveMemberDiagnostics.OwnerMustInheritRecursiveObservable, declaration.Location?.ToLocation(), declaration.DisplayName));

                hasErrors = true;
            }

            foreach (RecursiveMemberModel member in ownerMembers)
            {
                foreach (DiagnosticInfo diagnostic in member.Diagnostics)
                    context.ReportDiagnostic(diagnostic.ToDiagnostic());

                hasErrors |= member.HasErrors;
            }

            if (hasErrors)
                continue;

            var source = GenerateType(owner, ownerMembers);

            context.AddSource(declaration.HintName, SourceText.From(source, Encoding.UTF8));
        }
    }

    /// <summary>The members by owning type, in the order the types first appear; a type is keyed by its hint name, one per type.</summary>
    private static List<(RecursiveOwnerModel Owner, List<RecursiveMemberModel> Items)> GroupByOwner(ImmutableArray<RecursiveMemberModel> members)
    {
        HintNameGroups<RecursiveOwnerModel, RecursiveMemberModel> groups = new();

        foreach (RecursiveMemberModel member in members)
            groups.GetOrAdd(member.Owner, member.Owner.Declaration).Add(member);

        return groups.Groups;
    }

    private static string GenerateType(RecursiveOwnerModel owner, List<RecursiveMemberModel> members)
    {
        StringBuilder builder = new();

        _ = builder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        if (owner.Declaration.Namespace is not null)
        {
            _ = builder.Append("namespace ").Append(owner.Declaration.Namespace).AppendLine(";");
            _ = builder.AppendLine();
        }

        TypeDeclarationWriter.WriteTypeStart(builder, owner.Declaration.Declarations);

        var hasContent = false;

        GenerateInitializationConstructor(builder, owner, ref hasContent);

        foreach (RecursiveMemberModel member in members)
            GenerateSegmentField(builder, member, ref hasContent);

        foreach (RecursiveMemberModel member in members)
        {
            if (member.Generate)
                GenerateGeneratedProperty(builder, member, ref hasContent);
        }

        GeneratePropagateNotifier(builder, members, ref hasContent);
        GenerateTryGetValueCore(builder, members, ref hasContent);
        GenerateTrySetValueCore(builder, members, ref hasContent);

        TypeDeclarationWriter.WriteTypeEnd(builder, owner.Declaration.Declarations);

        return builder.ToString();
    }

    private static void GenerateInitializationConstructor(StringBuilder builder, RecursiveOwnerModel owner, ref bool hasContent)
    {
        if (owner.ConstructorAccessibility is null)
            return;

        TypeDeclarationWriter.AppendMemberSeparator(builder, ref hasContent);

        _ = builder
            .Append("    ")
            .Append(owner.ConstructorAccessibility)
            .Append(' ')
            .Append(owner.Name)
            .AppendLine("()");

        _ = builder
            .AppendLine("    {")
            .AppendLine("        ResetNotifier();")
            .AppendLine("    }");
    }

    private static void GenerateSegmentField(StringBuilder builder, RecursiveMemberModel model, ref bool hasContent)
    {
        var segmentFieldName = RecursiveMemberNames.GetSegmentFieldName(model.Name);

        TypeDeclarationWriter.AppendMemberSeparator(builder, ref hasContent);

        _ = builder
            .Append("    private static readonly ")
            .Append(RecursiveMemberNames.PathSegmentTypeName)
            .Append(' ')
            .Append(segmentFieldName)
            .Append(" = ")
            .Append(RecursiveMemberNames.PathSegmentTypeName)
            .Append(".ForProperty(nameof(")
            .Append(model.Name)
            .AppendLine("));");
    }

    private static void GenerateGeneratedProperty(StringBuilder builder, RecursiveMemberModel model, ref bool hasContent)
    {
        var propertyName = model.Name;
        var segmentFieldName = RecursiveMemberNames.GetSegmentFieldName(propertyName);

        TypeDeclarationWriter.AppendMemberSeparator(builder, ref hasContent);

        _ = builder
            .Append("    ")
            .Append(model.PropertyAccessibility)
            .Append(' ');

        if (model.PropertyModifiers.Length != 0)
            _ = builder.Append(model.PropertyModifiers).Append(' ');

        _ = builder
            .Append("partial ")
            .Append(model.Type)
            .Append(' ')
            .Append(propertyName)
            .AppendLine();

        _ = builder
            .AppendLine("    {");

        _ = builder.Append("        ");

        if (model.GetterAccessibility.Length != 0)
            _ = builder.Append(model.GetterAccessibility).Append(' ');

        _ = builder.AppendLine("get => field;");

        _ = builder.Append("        ");

        if (model.SetterAccessibility.Length != 0)
            _ = builder.Append(model.SetterAccessibility).Append(' ');

        _ = builder
            .Append("set => SetRecursiveProperty(ref field, value, ")
            .Append(segmentFieldName)
            .AppendLine(");");

        _ = builder.AppendLine("    }");
    }

    private static void GeneratePropagateNotifier(StringBuilder builder, List<RecursiveMemberModel> members, ref bool hasContent)
    {
        TypeDeclarationWriter.AppendMemberSeparator(builder, ref hasContent);

        _ = builder
            .AppendLine("    /// <inheritdoc/>")
            .Append("    protected override void PropagateNotifier(global::System.Collections.Generic.HashSet<")
            .Append(RecursiveMemberNames.RecursiveObservableTypeName)
            .AppendLine("> visited)");

        _ = builder
            .AppendLine("    {")
            .AppendLine("        base.PropagateNotifier(visited);");

        foreach (RecursiveMemberModel member in members)
        {
            if (!member.CanHoldRecursiveObservable)
                continue;

            var propertyName = member.Name;
            var segmentFieldName = RecursiveMemberNames.GetSegmentFieldName(propertyName);
            var localName = "__recursive" + propertyName + "Child";

            _ = builder.AppendLine();

            _ = builder
                .Append("        if (")
                .Append(propertyName)
                .Append(" is ")
                .Append(RecursiveMemberNames.RecursiveObservableTypeName)
                .Append(' ')
                .Append(localName)
                .AppendLine(")");

            _ = builder
                .Append("            AttachChild(")
                .Append(segmentFieldName)
                .Append(", ")
                .Append(localName)
                .AppendLine(", visited);");
        }

        _ = builder.AppendLine("    }");
    }

    private static void GenerateTryGetValueCore(StringBuilder builder, List<RecursiveMemberModel> members, ref bool hasContent)
    {
        TypeDeclarationWriter.AppendMemberSeparator(builder, ref hasContent);

        _ = builder
            .AppendLine("    /// <inheritdoc/>")
            .Append("    protected override bool TryGetValueCore(global::System.ReadOnlySpan<")
            .Append(RecursiveMemberNames.PathSegmentTypeName)
            .AppendLine("> segments, int offset, out object? value)");

        _ = builder
            .AppendLine("    {")
            .AppendLine("        if (offset >= segments.Length)")
            .AppendLine("            return base.TryGetValueCore(segments, offset, out value);")
            .AppendLine();

        _ = builder
            .Append("        ")
            .Append(RecursiveMemberNames.PathSegmentTypeName)
            .AppendLine(" segment = segments[offset];");

        _ = builder.AppendLine();

        _ = builder
            .Append("        if (segment.Kind != ")
            .Append(RecursiveMemberNames.PathSegmentKindTypeName)
            .AppendLine(".Property)");

        _ = builder.AppendLine("            return base.TryGetValueCore(segments, offset, out value);");

        foreach (RecursiveMemberModel member in members)
            GenerateTryGetBranch(builder, member);

        _ = builder
            .AppendLine()
            .AppendLine("        return base.TryGetValueCore(segments, offset, out value);")
            .AppendLine("    }");
    }

    private static void GenerateTryGetBranch(StringBuilder builder, RecursiveMemberModel member)
    {
        var propertyName = member.Name;
        var recursive = member.CanHoldRecursiveObservable;

        _ = builder.AppendLine();

        _ = builder
            .Append("        if (global::System.StringComparer.Ordinal.Equals(segment.Property, nameof(")
            .Append(propertyName)
            .AppendLine(")))");

        _ = builder
            .AppendLine("        {")
            .AppendLine("            if (offset == segments.Length - 1)")
            .AppendLine("            {")
            .Append("                value = ")
            .Append(propertyName)
            .AppendLine(";")
            .AppendLine("                return true;")
            .AppendLine("            }");

        if (recursive)
        {
            _ = builder.AppendLine();

            _ = builder
                .Append("            if (")
                .Append(propertyName)
                .Append(" is ")
                .Append(RecursiveMemberNames.RecursiveObservableTypeName)
                .AppendLine(" recursive)");

            _ = builder.AppendLine("                return TryGetNestedValue(recursive, segments, offset + 1, out value);");
        }

        _ = builder
            .AppendLine()
            .AppendLine("            value = null;")
            .AppendLine("            return false;")
            .AppendLine("        }");
    }

    private static void GenerateTrySetValueCore(StringBuilder builder, List<RecursiveMemberModel> members, ref bool hasContent)
    {
        TypeDeclarationWriter.AppendMemberSeparator(builder, ref hasContent);

        _ = builder
            .AppendLine("    /// <inheritdoc/>")
            .Append("    protected override bool TrySetValueCore(global::System.ReadOnlySpan<")
            .Append(RecursiveMemberNames.PathSegmentTypeName)
            .AppendLine("> segments, int offset, object? value)");

        _ = builder
            .AppendLine("    {")
            .AppendLine("        if (offset >= segments.Length)")
            .AppendLine("            return false;")
            .AppendLine();

        _ = builder
            .Append("        ")
            .Append(RecursiveMemberNames.PathSegmentTypeName)
            .AppendLine(" segment = segments[offset];");

        _ = builder.AppendLine();

        _ = builder
            .Append("        if (segment.Kind != ")
            .Append(RecursiveMemberNames.PathSegmentKindTypeName)
            .AppendLine(".Property)");

        _ = builder.AppendLine("            return base.TrySetValueCore(segments, offset, value);");

        foreach (RecursiveMemberModel member in members)
            GenerateTrySetBranch(builder, member);

        _ = builder
            .AppendLine()
            .AppendLine("        return base.TrySetValueCore(segments, offset, value);")
            .AppendLine("    }");
    }

    private static void GenerateTrySetBranch(StringBuilder builder, RecursiveMemberModel member)
    {
        var propertyName = member.Name;
        var patternType = member.PatternType;

        var recursive = member.CanHoldRecursiveObservable;
        var canSet = member.CanSet;
        var isNullable = member.IsNullable;

        _ = builder.AppendLine();

        _ = builder
            .Append("        if (global::System.StringComparer.Ordinal.Equals(segment.Property, nameof(")
            .Append(propertyName)
            .AppendLine(")))");

        _ = builder
            .AppendLine("        {")
            .AppendLine("            if (offset != segments.Length - 1)")
            .AppendLine("            {");

        if (recursive)
        {
            _ = builder
                .Append("                if (")
                .Append(propertyName)
                .Append(" is ")
                .Append(RecursiveMemberNames.RecursiveObservableTypeName)
                .AppendLine(" recursive)");

            _ = builder
                .AppendLine("                    return TrySetNestedValue(recursive, segments, offset + 1, value);")
                .AppendLine();
        }

        _ = builder
            .AppendLine("                return false;")
            .AppendLine("            }");

        if (!canSet)
        {
            _ = builder
                .AppendLine()
                .AppendLine("            return false;")
                .AppendLine("        }");
            return;
        }

        _ = builder.AppendLine();

        if (isNullable)
        {
            _ = builder
                .AppendLine("            if (value is null)")
                .AppendLine("            {")
                .Append("                ")
                .Append(propertyName)
                .AppendLine(" = default;")
                .AppendLine("                return true;")
                .AppendLine("            }")
                .AppendLine();
        }
        else
        {
            _ = builder
                .AppendLine("            if (value is null)")
                .AppendLine("                return false;")
                .AppendLine();
        }

        _ = builder
            .Append("            if (value is not ")
            .Append(patternType)
            .Append(" typedValue && !global::NE.Standard.UI.Abstractions.Recursive.RecursiveValueCoercion.TryCoerce(value, out typedValue))")
            .AppendLine()
            .AppendLine("                return false;")
            .AppendLine();

        _ = builder
            .Append("            ")
            .Append(propertyName)
            .AppendLine(" = typedValue;")
            .AppendLine("            return true;")
            .AppendLine("        }");
    }
}
